### ISSUE TITLE
Keep Ids intact

### ISSUE THREAD

**Issue by niccokunzmann** [thoka/ical-filter#3]
Since this is a filter and no modification, the ids should be kept identical.

`UID:7uartkcnhf0elbvs8md0itrf6c@google.com+(ccc%7Cchaos)`

**Comment by thoka** [comment]
Hm. Google for example wont show up events in different calendars with same UID. So you would miss same events, if one of these calendars is hidden and the other one is not showing this event.
But this could be an configuration option and switched on by default.

**Comment by niccokunzmann** [comment]
So, if I have the same event in different calendars, only one will show it? Okay, maybe I misunderstood the UID property.  You can close the issue if you see it fit.

**Comment by thoka** [comment]
Closing. 
File a new issue if you need need a configuration option to keep UIDs unchanged.
